### ISSUE TITLE
Support btrfs graph driver

### ISSUE THREAD

**Issue by matthyx** [kubernetes/system-validators#21]
Hello,
I can make a PR to add it to the list, but is there any downside?
https://github.com/kubernetes/system-validators/blob/master/validators/types_unix.go#L74

More details on the driver itself:
https://docs.docker.com/storage/storagedriver/btrfs-driver/

**Comment by neolit123** [comment]
cc @KentaTada @odinuge

**Comment by KentaTada** [comment]
I am not familiar with the status of btrfs integration but it seems that the current k8s has the problem to integrate with btrfs because of the cAdvisor's issue.
https://github.com/kubernetes/kubernetes/issues/94335#issuecomment-747392517

If we add btrfs to the list, I think we need to wait for k8s v1.21 at least.

**Comment by matthyx** [comment]
Thanks, let's wait and see...

**Comment by neolit123** [comment]
I think the cadvisor problems are resolved. A bit hard to tell if btrfs is working now...

I think the important part is that it is claimed as supported, thus we should enable it here.

/remove-lifecycle stale

**Comment by neolit123** [comment]
https://github.com/kubernetes/system-validators/pull/26
merged
