### ISSUE TITLE
kernel cgroup v2 support update

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/system-validators#28]
https://github.com/kubernetes/system-validators/blob/73d9d3d9f43503b1a64ec0506080252c683f8408/validators/types_unix.go#L65-L77

Need we update it?

- blkio: As I know, iops cgroupv2 needs `blkio` once https://github.com/containerd/containerd/pull/5490 is ready. 

like hugetlb: huge page support is optional.

**Comment by neolit123** [comment]
i'm not sure, @KentaTada @odinuge WDYT?
aslo, isn't blkio in cgroups v1 as well?
https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/blkio-controller.html

> {Name: "CGROUP_HUGETLB", Description: "Required for hugetlb cgroup."},

hugetlb is optional and if blkio falls in the same bucket we can add it.

**Comment by KentaTada** [comment]
If we add blkio in v2, we also need to add it in v1.
But I think hugetlb was added because hugetlb has been already supported by kubelet.
My understanding is that the activity of blkio support for k/k is under discussion. 
https://github.com/kubernetes/enhancements/pull/1907

I think when the above activity for k/k is finished is the right timing.

**Comment by pacoxu** [comment]
> I think when the above activity for k/k is finished is the right timing.

Agree. I opened this issue for that KEP.

**Comment by neolit123** [comment]
Ok, thank you for checking, @KentaTada
And @pacoxu thank you for your work on enabling this in k8s. Let's see how things go.

Having it as optional makes sense.
